<?php

########################################################################
# Extension Manager/Repository config file for ext: "import_excel"
#
# Auto generated by Extension Builder 2013-11-13
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Import Excel files to database',
	'description' => 'Import Excel files to database, based on PHPExcel Library',
	'category' => 'module',
	'author' => 'Andrea Schmuttermair',
	'author_email' => 'spam@schmutt.de',
	'author_company' => 'Schmuttermair Software',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3.0-6.2.99',
			'fluid' => '1.3.0-6.2.99',
			'typo3' => '4.5.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>